cluster:
  domain: {{ .Requirements.ingress.domain }}
{{- if hasKey .Requirements.cluster "project" }}
  projectID: {{ .Requirements.cluster.project }}
{{- else }}
  projectID: ""
{{- end }}

 {{- if .Requirements.ingress.tls }}
certmanager:
  production: "{{ .Requirements.ingress.tls.production }}"
{{- if .Requirements.ingress.tls.enabled }}
  email:  "{{ .Requirements.ingress.tls.email }}"
{{- else }}
  enabled: false
{{- end }}
{{- end }}
